import type { Scenario, ScenarioStep } from "./types.js";

function jsStr(v: string | undefined): string {
  return JSON.stringify(v ?? "");
}

function stepToLine(step: ScenarioStep): string {
  const sel = step.selector ? jsStr(step.selector) : undefined;
  const comment = step.selectorLabel ? `  // ${step.selectorLabel}` : "";

  switch (step.type) {
    case "goto":
      return `  await page.goto(${jsStr(step.url)});${comment}`;
    case "click":
      return `  await page.locator(${sel}).click();${comment}`;
    case "dblclick":
      return `  await page.locator(${sel}).dblclick();${comment}`;
    case "fill":
      if (step.redacted) {
        return (
          `  await page.locator(${sel}).fill(process.env.QUALIMETRY_SECRET ?? "");` +
          `  // ⚠ ${step.selectorLabel ?? "sensitive field"} — value was not recorded; set QUALIMETRY_SECRET`
        );
      }
      return `  await page.locator(${sel}).fill(${jsStr(step.value)});${comment}`;
    case "check":
      return `  await page.locator(${sel}).check();${comment}`;
    case "uncheck":
      return `  await page.locator(${sel}).uncheck();${comment}`;
    case "select":
      return `  await page.locator(${sel}).selectOption(${jsStr(step.value)});${comment}`;
    case "press":
      return sel
        ? `  await page.locator(${sel}).press(${jsStr(step.value)});${comment}`
        : `  await page.keyboard.press(${jsStr(step.value)});${comment}`;
    case "assertText":
      return `  await expect(page.locator(${sel})).toHaveText(${jsStr(step.value)});${comment}`;
    case "assertVisible":
      return `  await expect(page.locator(${sel})).toBeVisible();${comment}`;
    case "assertUrl":
      return `  await expect(page).toHaveURL(${jsStr(step.url)});${comment}`;
    default:
      return `  // Unsupported step type: ${step.type}`;
  }
}

/** Renders a Scenario as a runnable @playwright/test spec file. */
export function generateSpec(scenario: Scenario): string {
  const lines = scenario.steps.map(stepToLine);
  const header = [
    `import { test, expect } from "@playwright/test";`,
    ``,
    `// Generated by qualimetry from scenario "${scenario.name}".`,
    `// Recorded against: ${scenario.baseUrl}`,
    scenario.description ? `// ${scenario.description}` : undefined,
    ``,
    `test(${jsStr(scenario.name)}, async ({ page }) => {`,
  ].filter((l): l is string => l !== undefined);

  return [...header, ...lines, `});`, ``].join("\n");
}
