-- ==================================================================
--  [02] NEW TABLES  (34)
--  Safe — tables do not exist in MOAMALAT yet
--  Target schema : MOAMALAT
--  Run as        : DBA or MOAMALAT user
-- ==================================================================

-- NEW TABLE: T_FLYWAY_DML_BCKP_07_04_2026
CREATE TABLE "T_FLYWAY_DML_BCKP_07_04_2026" 
   (	"installed_rank" NUMBER(*,0) NOT NULL ENABLE,
	"version" VARCHAR2(50),
	"description" VARCHAR2(200) NOT NULL ENABLE,
	"type" VARCHAR2(20) NOT NULL ENABLE,
	"script" VARCHAR2(1000) NOT NULL ENABLE,
	"checksum" NUMBER(*,0),
	"installed_by" VARCHAR2(100) NOT NULL ENABLE,
	"installed_on" TIMESTAMP(6) NOT NULL ENABLE,
	"execution_time" NUMBER(*,0) NOT NULL ENABLE,
	"success" NUMBER(1,0) NOT NULL ENABLE
   );

-- NEW TABLE: T_FLYWAY_DDL_BCKP_07_04_2026
CREATE TABLE "T_FLYWAY_DDL_BCKP_07_04_2026" 
   (	"installed_rank" NUMBER(*,0) NOT NULL ENABLE,
	"version" VARCHAR2(50),
	"description" VARCHAR2(200) NOT NULL ENABLE,
	"type" VARCHAR2(20) NOT NULL ENABLE,
	"script" VARCHAR2(1000) NOT NULL ENABLE,
	"checksum" NUMBER(*,0),
	"installed_by" VARCHAR2(100) NOT NULL ENABLE,
	"installed_on" TIMESTAMP(6) NOT NULL ENABLE,
	"execution_time" NUMBER(*,0) NOT NULL ENABLE,
	"success" NUMBER(1,0) NOT NULL ENABLE
   );

-- NEW TABLE: PPA_USERS_MAPPING_OLD
CREATE TABLE "PPA_USERS_MAPPING_OLD" 
   (	"USR_LOGIN" VARCHAR2(26),
	"USR_UDF_EMP_ID" NUMBER(38,0),
	"USR_STATUS" VARCHAR2(26)
   );

-- NEW TABLE: PE_MAPPING
CREATE TABLE "PE_MAPPING" 
   (	"F_USERNAME" VARCHAR2(26),
	"F_USERID" NUMBER,
	"MAPPED_F_USERNAME" VARCHAR2(30),
	"MAPPED_F_USERID" NUMBER
   );

-- NEW TABLE: PEALLUSERS
CREATE TABLE "PEALLUSERS" 
   (	"F_USERNAME" VARCHAR2(30),
	"F_USERID" VARCHAR2(30),
	"F_TIMESTAMP" VARCHAR2(100),
	"F_DN" VARCHAR2(350),
	"F_SID" VARCHAR2(350)
   );

-- NEW TABLE: OSAMATEST
CREATE TABLE "OSAMATEST" 
   (	"ID" NUMBER,
	"NAME" VARCHAR2(50)
   );

-- NEW TABLE: IO_SECTORS_BCK29_08_2024
CREATE TABLE "IO_SECTORS_BCK29_08_2024" 
   (	"SECTOR_ID" NUMBER NOT NULL ENABLE,
	"SECTOR_NAME" VARCHAR2(100) NOT NULL ENABLE
   );

-- NEW TABLE: IO_SECTORS_17_4_2025
CREATE TABLE "IO_SECTORS_17_4_2025" 
   (	"SECTOR_ID" NUMBER NOT NULL ENABLE,
	"SECTOR_NAME" VARCHAR2(100) NOT NULL ENABLE
   );

-- NEW TABLE: IO_REMINDER_20250820
CREATE TABLE "IO_REMINDER_20250820" 
   (	"ID" VARCHAR2(50),
	"CORRESPONDENCENUMBER" NUMBER,
	"HIJRICYEAR" NUMBER,
	"TYPEID" NUMBER,
	"USERID" VARCHAR2(20),
	"REMINDERDATE" VARCHAR2(50),
	"ISCLOSED" NUMBER,
	"REMINDERCREATOR" VARCHAR2(20),
	"REMINDERTO" VARCHAR2(1500),
	"ISCREATOR" NUMBER,
	"ESCALATION" NUMBER,
	"TEST" NUMBER,
	"DAYS" NUMBER,
	"SUBJECT" VARCHAR2(500),
	"VERY_URGENT" NUMBER,
	"MESSAGE_CONTENT" VARCHAR2(1000)
   );

-- NEW TABLE: IO_EXTERNALUNITS_BACKUP_20230601
CREATE TABLE "IO_EXTERNALUNITS_BACKUP_20230601" 
   (	"EXTERNALUNITID" NUMBER NOT NULL ENABLE,
	"EXTERNALUNITDESC" VARCHAR2(400) NOT NULL ENABLE,
	"EXTERNALUNITTYPE" NUMBER NOT NULL ENABLE,
	"MOCODE" NUMBER NOT NULL ENABLE,
	"ORG_CODE" VARCHAR2(20),
	"NCAR" NUMBER,
	"MURASALAT_MEMBER" NUMBER,
	"SUB_ID" NUMBER,
	"SYSTEMTYPE" NUMBER
   );

-- NEW TABLE: IO_EMPLOYEES_PROD_2024_11_11
CREATE TABLE "IO_EMPLOYEES_PROD_2024_11_11" 
   (	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"NATIONALNUMBER" NUMBER,
	"FULLNAME" VARCHAR2(250),
	"USERID" VARCHAR2(50),
	"DEPARTMENTID" NUMBER,
	"JOBTITLE" VARCHAR2(500),
	"ISACTIVE" NUMBER DEFAULT 1 NOT NULL ENABLE,
	"BACKUP_SIGNER_EMP_ID" NUMBER,
	"PHONENO" VARCHAR2(20 CHAR),
	"EMAIL" VARCHAR2(100),
	"SYSTEMTYPE" NUMBER DEFAULT 0
   );

-- NEW TABLE: IO_EMPLOYEES_BKP_5_JAN_2025
CREATE TABLE "IO_EMPLOYEES_BKP_5_JAN_2025" 
   (	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"NATIONALNUMBER" NUMBER,
	"FULLNAME" VARCHAR2(250),
	"USERID" VARCHAR2(50),
	"DEPARTMENTID" NUMBER,
	"JOBTITLE" VARCHAR2(500),
	"ISACTIVE" NUMBER NOT NULL ENABLE,
	"BACKUP_SIGNER_EMP_ID" NUMBER,
	"PHONENO" VARCHAR2(20 CHAR),
	"EMAIL" VARCHAR2(100),
	"SYSTEMTYPE" NUMBER
   );

-- NEW TABLE: IO_EMPLOYEES_BCK29_08_2024
CREATE TABLE "IO_EMPLOYEES_BCK29_08_2024" 
   (	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"NATIONALNUMBER" NUMBER,
	"FULLNAME" VARCHAR2(250),
	"USERID" VARCHAR2(50),
	"DEPARTMENTID" NUMBER,
	"JOBTITLE" VARCHAR2(500),
	"ISACTIVE" NUMBER NOT NULL ENABLE,
	"BACKUP_SIGNER_EMP_ID" NUMBER,
	"PHONENO" VARCHAR2(20 CHAR),
	"EMAIL" VARCHAR2(100),
	"SYSTEMTYPE" NUMBER
   );

-- NEW TABLE: IO_EMPLOYEES_2025_04_17
CREATE TABLE "IO_EMPLOYEES_2025_04_17" 
   (	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"NATIONALNUMBER" NUMBER,
	"FULLNAME" VARCHAR2(250),
	"USERID" VARCHAR2(50),
	"DEPARTMENTID" NUMBER,
	"JOBTITLE" VARCHAR2(500),
	"ISACTIVE" NUMBER NOT NULL ENABLE,
	"BACKUP_SIGNER_EMP_ID" NUMBER,
	"PHONENO" VARCHAR2(20 CHAR),
	"EMAIL" VARCHAR2(100),
	"SYSTEMTYPE" NUMBER
   );

-- NEW TABLE: IO_EMPLOYEES_17_4_2025
CREATE TABLE "IO_EMPLOYEES_17_4_2025" 
   (	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"NATIONALNUMBER" NUMBER,
	"FULLNAME" VARCHAR2(250),
	"USERID" VARCHAR2(50),
	"DEPARTMENTID" NUMBER,
	"JOBTITLE" VARCHAR2(500),
	"ISACTIVE" NUMBER NOT NULL ENABLE,
	"BACKUP_SIGNER_EMP_ID" NUMBER,
	"PHONENO" VARCHAR2(20 CHAR),
	"EMAIL" VARCHAR2(100),
	"SYSTEMTYPE" NUMBER
   );

-- NEW TABLE: IO_EMPLOYEESCONFIGS_BCK29_08_2024
CREATE TABLE "IO_EMPLOYEESCONFIGS_BCK29_08_2024" 
   (	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"ENABLEDOPTIONSMASK" NUMBER NOT NULL ENABLE,
	"MOSORTORDER" NUMBER,
	"ACSORTORDER" NUMBER,
	"FORWARDINGTOLIST" NUMBER NOT NULL ENABLE,
	"SYSTEMTYPE" VARCHAR2(20)
   );

-- NEW TABLE: IO_EMPLOYEESCONFIGS_2025_04_17
CREATE TABLE "IO_EMPLOYEESCONFIGS_2025_04_17" 
   (	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"ENABLEDOPTIONSMASK" NUMBER NOT NULL ENABLE,
	"MOSORTORDER" NUMBER,
	"ACSORTORDER" NUMBER,
	"FORWARDINGTOLIST" NUMBER NOT NULL ENABLE,
	"SYSTEMTYPE" VARCHAR2(20)
   );

-- NEW TABLE: IO_EMPLOYEESCONFIGS_17_4_2025
CREATE TABLE "IO_EMPLOYEESCONFIGS_17_4_2025" 
   (	"EMPLOYEEID" NUMBER NOT NULL ENABLE,
	"ENABLEDOPTIONSMASK" NUMBER NOT NULL ENABLE,
	"MOSORTORDER" NUMBER,
	"ACSORTORDER" NUMBER,
	"FORWARDINGTOLIST" NUMBER NOT NULL ENABLE,
	"SYSTEMTYPE" VARCHAR2(20)
   );

-- NEW TABLE: IO_DEPARTMENTS_BKP_5_JAN_2025
CREATE TABLE "IO_DEPARTMENTS_BKP_5_JAN_2025" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"DEPARTMENTNAME" VARCHAR2(250),
	"MANAGERID" NUMBER,
	"REPRESENTATIVEID" NUMBER,
	"PARENTDEPARTMENTID" NUMBER,
	"DEPARTMENTLEVEL" NUMBER,
	"CANACCESSSYSTEM" NUMBER,
	"DEPARTMENTCODE" VARCHAR2(20) NOT NULL ENABLE,
	"ISACTIVE" NUMBER NOT NULL ENABLE,
	"SYMBOL" VARCHAR2(3),
	"SECTOR_ID" NUMBER,
	"EBS_DEPARTMENT_ID" NUMBER,
	"ARCHIVE_PAGE_URL" VARCHAR2(200),
	"PENSION_COMM_DEPT" NUMBER NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTS_BCK29_08_2024
CREATE TABLE "IO_DEPARTMENTS_BCK29_08_2024" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"DEPARTMENTNAME" VARCHAR2(250),
	"MANAGERID" NUMBER,
	"REPRESENTATIVEID" NUMBER,
	"PARENTDEPARTMENTID" NUMBER,
	"DEPARTMENTLEVEL" NUMBER,
	"CANACCESSSYSTEM" NUMBER,
	"DEPARTMENTCODE" VARCHAR2(20) NOT NULL ENABLE,
	"ISACTIVE" NUMBER NOT NULL ENABLE,
	"SYMBOL" VARCHAR2(3),
	"SECTOR_ID" NUMBER,
	"EBS_DEPARTMENT_ID" NUMBER,
	"ARCHIVE_PAGE_URL" VARCHAR2(200),
	"PENSION_COMM_DEPT" NUMBER NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTS_2025_05_12
CREATE TABLE "IO_DEPARTMENTS_2025_05_12" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"DEPARTMENTNAME" VARCHAR2(250),
	"MANAGERID" NUMBER,
	"REPRESENTATIVEID" NUMBER,
	"PARENTDEPARTMENTID" NUMBER,
	"DEPARTMENTLEVEL" NUMBER,
	"CANACCESSSYSTEM" NUMBER,
	"DEPARTMENTCODE" VARCHAR2(20) NOT NULL ENABLE,
	"ISACTIVE" NUMBER NOT NULL ENABLE,
	"SYMBOL" VARCHAR2(3),
	"SECTOR_ID" NUMBER,
	"EBS_DEPARTMENT_ID" NUMBER,
	"ARCHIVE_PAGE_URL" VARCHAR2(200),
	"PENSION_COMM_DEPT" NUMBER NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTS_2025_04_17
CREATE TABLE "IO_DEPARTMENTS_2025_04_17" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"DEPARTMENTNAME" VARCHAR2(250),
	"MANAGERID" NUMBER,
	"REPRESENTATIVEID" NUMBER,
	"PARENTDEPARTMENTID" NUMBER,
	"DEPARTMENTLEVEL" NUMBER,
	"CANACCESSSYSTEM" NUMBER,
	"DEPARTMENTCODE" VARCHAR2(20) NOT NULL ENABLE,
	"ISACTIVE" NUMBER NOT NULL ENABLE,
	"SYMBOL" VARCHAR2(3),
	"SECTOR_ID" NUMBER,
	"EBS_DEPARTMENT_ID" NUMBER,
	"ARCHIVE_PAGE_URL" VARCHAR2(200),
	"PENSION_COMM_DEPT" NUMBER NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTS_17_4_2025
CREATE TABLE "IO_DEPARTMENTS_17_4_2025" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"DEPARTMENTNAME" VARCHAR2(250),
	"MANAGERID" NUMBER,
	"REPRESENTATIVEID" NUMBER,
	"PARENTDEPARTMENTID" NUMBER,
	"DEPARTMENTLEVEL" NUMBER,
	"CANACCESSSYSTEM" NUMBER,
	"DEPARTMENTCODE" VARCHAR2(20) NOT NULL ENABLE,
	"ISACTIVE" NUMBER NOT NULL ENABLE,
	"SYMBOL" VARCHAR2(3),
	"SECTOR_ID" NUMBER,
	"EBS_DEPARTMENT_ID" NUMBER,
	"ARCHIVE_PAGE_URL" VARCHAR2(200),
	"PENSION_COMM_DEPT" NUMBER NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTSCONFIGS_BKP_5_JAN_2025
CREATE TABLE "IO_DEPARTMENTSCONFIGS_BKP_5_JAN_2025" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"ENABLEDOPTIONSMASK" NUMBER NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTSCONFIGS_2025_04_17
CREATE TABLE "IO_DEPARTMENTSCONFIGS_2025_04_17" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"ENABLEDOPTIONSMASK" NUMBER NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTSCONFIGS_17_4_2025
CREATE TABLE "IO_DEPARTMENTSCONFIGS_17_4_2025" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"ENABLEDOPTIONSMASK" NUMBER NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTSCONFIGSBCK_29_08_2024
CREATE TABLE "IO_DEPARTMENTSCONFIGSBCK_29_08_2024" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"ENABLEDOPTIONSMASK" NUMBER NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTQUEUES_20260208
CREATE TABLE "IO_DEPARTMENTQUEUES_20260208" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"DEPARTMENTNAMEAR" VARCHAR2(500) NOT NULL ENABLE,
	"DEPARTMENTNAMEEN" VARCHAR2(500) NOT NULL ENABLE,
	"QUEUENAME" VARCHAR2(250) NOT NULL ENABLE,
	"QUEUESHORTNAME" VARCHAR2(250) NOT NULL ENABLE
   );

-- NEW TABLE: IO_DEPARTMENTQUEUES_2025_04_17
CREATE TABLE "IO_DEPARTMENTQUEUES_2025_04_17" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"DEPARTMENTNAMEAR" VARCHAR2(500) NOT NULL ENABLE,
	"DEPARTMENTNAMEEN" VARCHAR2(500) NOT NULL ENABLE,
	"QUEUENAME" VARCHAR2(250) NOT NULL ENABLE,
	"QUEUESHORTNAME" VARCHAR2(250) NOT NULL ENABLE
   );

-- NEW TABLE: FILE_ACCESS_REQUEST_BKP
CREATE TABLE "FILE_ACCESS_REQUEST_BKP" 
   (	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CORRESPONDENCE_NUMBER" NUMBER(19,0) NOT NULL ENABLE,
	"DECIDED_BY" VARCHAR2(50 CHAR),
	"DECISION_DATE" TIMESTAMP(6),
	"DOCUMENT_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE,
	"REASON" VARCHAR2(500 CHAR),
	"REQUESTED_BY" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"REQUESTED_TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"STATUS" VARCHAR2(20 CHAR)
   );

-- NEW TABLE: FILE_ACCESS_BKP
CREATE TABLE "FILE_ACCESS_BKP" 
   (	"ASSIGNED_USER_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CORRESPONDENCE_NUMBER" NUMBER(19,0) NOT NULL ENABLE,
	"DOCUMENT_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"ASSIGNED_AT" TIMESTAMP(6),
	"ASSIGNED_BY" VARCHAR2(255 CHAR),
	"CLASSIFICATION_TYPE" VARCHAR2(255 CHAR),
	"PERMISSION_TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"OWNER" VARCHAR2(255 CHAR)
   );

-- NEW TABLE: EMPLOYEE_DELEGATION_BACKUP_2026_03_09
CREATE TABLE "EMPLOYEE_DELEGATION_BACKUP_2026_03_09" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"USER_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"DELEGATE_USER_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"START_DATE" DATE NOT NULL ENABLE,
	"END_DATE" DATE,
	"RECEIVE_SELF" NUMBER(1,0) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(2000 CHAR),
	"DELEGATION_TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"ON_BEHALF_LOGGING" NUMBER(1,0) NOT NULL ENABLE,
	"CREATED_AT" DATE NOT NULL ENABLE,
	"UPDATED_AT" DATE,
	"APPROVAL_STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE
   );

-- NEW TABLE: EMPLOYEE_DELEGATION_BACKUO_2026_02_18
CREATE TABLE "EMPLOYEE_DELEGATION_BACKUO_2026_02_18" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"USER_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"DELEGATE_USER_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"START_DATE" DATE NOT NULL ENABLE,
	"END_DATE" DATE,
	"RECEIVE_SELF" NUMBER(1,0) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(2000 CHAR),
	"DELEGATION_TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"ON_BEHALF_LOGGING" NUMBER(1,0) NOT NULL ENABLE,
	"CREATED_AT" DATE NOT NULL ENABLE,
	"UPDATED_AT" DATE
   );

-- NEW TABLE: ARCHIVE_INCOMING_SEQUENCE_CONFIDENTIAL-deletethis
CREATE TABLE "ARCHIVE_INCOMING_SEQUENCE_CONFIDENTIAL-deletethis" 
   (	"SEQUENCE_NO" NUMBER NOT NULL ENABLE,
	"HIJRIC_YEAR" NUMBER(4,0) NOT NULL ENABLE
   );
