-- ==================================================================
--  [03] CHANGED TABLES — SAFE  (169)
--  ADD column / DEFAULT changes — safe to run
--  Target schema : MOAMALAT
--  Run as        : DBA or MOAMALAT user
-- ==================================================================

-- CHANGED TABLE: WF_WORKITEMS
ALTER TABLE "WF_WORKITEMS" ADD  PRIMARY KEY ("ID") ENABLE;

-- CHANGED TABLE: WF_DRAFTS_V
ALTER TABLE "WF_DRAFTS_V" ADD  PRIMARY KEY ("HIJRICYEAR","SEQUENCENUMBER","SRC_TYPE") ;

-- CHANGED TABLE: WCC_SEQUENCE
ALTER TABLE "WCC_SEQUENCE" ;

-- CHANGED TABLE: WCC_BATCH
ALTER TABLE "WCC_BATCH" ;

-- CHANGED TABLE: WCC
ALTER TABLE "WCC" STORAGE ( NEXT 1048576)  ;

-- CHANGED TABLE: VWUSERBACKUP
ALTER TABLE "VWUSERBACKUP" ;

-- CHANGED TABLE: USER_PREFERENCES
ALTER TABLE "USER_PREFERENCES" ;

-- CHANGED TABLE: USER_MENTIONS
ALTER TABLE "USER_MENTIONS" MODIFY ("CORRESPONDENCE_NUMBER" NUMBER);
ALTER TABLE "USER_MENTIONS" MODIFY ("CORRESPONDENCE_TYPE" NUMBER);
ALTER TABLE "USER_MENTIONS" MODIFY ("CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "USER_MENTIONS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
ALTER TABLE "USER_MENTIONS" MODIFY ("HIJRI_YEAR" NUMBER);
ALTER TABLE "USER_MENTIONS" MODIFY ("ID" NUMBER DEFAULT "ISEQ$$_193732".nextval);
ALTER TABLE "USER_MENTIONS" MODIFY ("ISDELETED" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "USER_MENTIONS" ADD CONSTRAINT "FK_USER_MENTIONS_PERM" FOREIGN KEY ("PERMISSION_LEVEL") REFERENCES "MENTION_PERMISSIONS"("CODE") ENABLE;
ALTER TABLE "USER_MENTIONS" ADD CONSTRAINT "CK_USER_MENTIONS_PERM" CHECK (PERMISSION_LEVEL IN ('VIEW_ONLY','VIEW_COMMENT','VIEW_UPLOAD')) ENABLE;

-- CHANGED TABLE: T_FLYWAY_DML
ALTER TABLE "T_FLYWAY_DML" ;

-- CHANGED TABLE: T_FLYWAY_DDL
ALTER TABLE "T_FLYWAY_DDL" ;

-- CHANGED TABLE: TT_VALUES2
ALTER TABLE "TT_VALUES2" ;

-- CHANGED TABLE: TEMPLATES
ALTER TABLE "TEMPLATES" ;

-- CHANGED TABLE: TASKS
ALTER TABLE "TASKS" MODIFY ("ASSIGNEE_ID" VARCHAR2(50));
ALTER TABLE "TASKS" MODIFY ("ASSIGNEE_ID" NULL);
ALTER TABLE "TASKS" MODIFY ("CORRESPONDENCE_SEQ" NOT NULL ENABLE);
ALTER TABLE "TASKS" MODIFY ("CORRESPONDENCE_TYPE" NUMBER(1,0));
ALTER TABLE "TASKS" MODIFY ("CORRESPONDENCE_YEAR" NUMBER(4,0));
ALTER TABLE "TASKS" MODIFY ("CORRESPONDENCE_YEAR" NOT NULL ENABLE);
ALTER TABLE "TASKS" MODIFY ("CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "TASKS" MODIFY ("CREATOR_ID" VARCHAR2(50));
ALTER TABLE "TASKS" MODIFY ("CREATOR_ID" NULL);
ALTER TABLE "TASKS" MODIFY ("DESCRIPTION" CLOB) LOB ("DESCRIPTION") STORE AS SECUREFILE  ( ENABLE STORAGE IN ROW CHUNK 8192 NOCACHE LOGGING  KEEP_DUPLICATES  STORAGE( INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT));
ALTER TABLE "TASKS" MODIFY ("ID" NUMBER DEFAULT "ISEQ$$_193883".nextval);
ALTER TABLE "TASKS" MODIFY ("IS_DELETED" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "TASKS" MODIFY ("PRIORITY" VARCHAR2(20 CHAR));
ALTER TABLE "TASKS" MODIFY ("STATUS" VARCHAR2(20 CHAR));
ALTER TABLE "TASKS" MODIFY ("TITLE" NOT NULL ENABLE);
ALTER TABLE "TASKS" ADD CONSTRAINT "CHK_TASKS_IS_DELETED" CHECK (IS_DELETED IN (0, 1)) ENABLE;

-- CHANGED TABLE: TABLE2
ALTER TABLE "TABLE2" ;

-- CHANGED TABLE: TABLE1
ALTER TABLE "TABLE1" ;

-- CHANGED TABLE: STUDENT_REQUEST_LOG
ALTER TABLE "STUDENT_REQUEST_LOG" ;

-- CHANGED TABLE: SIGNATURES
ALTER TABLE "SIGNATURES" ;

-- CHANGED TABLE: RASEL_ACTION_LOG
ALTER TABLE "RASEL_ACTION_LOG" ;

-- CHANGED TABLE: PPA_USERS_MAPPING
ALTER TABLE "PPA_USERS_MAPPING" ;

-- CHANGED TABLE: PPAINTEGRATIONWSLOG
ALTER TABLE "PPAINTEGRATIONWSLOG" ;

-- CHANGED TABLE: PPAINTEGRATIONWSDOCS
ALTER TABLE "PPAINTEGRATIONWSDOCS" ;

-- CHANGED TABLE: PENSION_DOC_TYPES
ALTER TABLE "PENSION_DOC_TYPES" ;

-- CHANGED TABLE: PENSIONER_INFO
ALTER TABLE "PENSIONER_INFO" ;

-- CHANGED TABLE: NEW_DEPARTMENT
ALTER TABLE "NEW_DEPARTMENT" ;

-- CHANGED TABLE: NCGR_EMPLOYEE
ALTER TABLE "NCGR_EMPLOYEE" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193615".nextval);
ALTER TABLE "NCGR_EMPLOYEE" ADD  PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "NCGR_EMPLOYEE" ADD CONSTRAINT "FKDPNCTUDGSL3D2I3CWXV78NEYE" FOREIGN KEY ("DEDUCTION_ID") REFERENCES "NCGR_DEDUCTION"("ID") ENABLE;

-- CHANGED TABLE: NCGR_DEDUCTION
ALTER TABLE "NCGR_DEDUCTION" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193644".nextval);
ALTER TABLE "NCGR_DEDUCTION" ADD  PRIMARY KEY ("ID") ENABLE;

-- CHANGED TABLE: MUURASALAT_PERSON_INFORMATION
ALTER TABLE "MUURASALAT_PERSON_INFORMATION" ;

-- CHANGED TABLE: MURASALAT_OUTGOING
ALTER TABLE "MURASALAT_OUTGOING" ;

-- CHANGED TABLE: MURASALAT_INCOMING
ALTER TABLE "MURASALAT_INCOMING" ;

-- CHANGED TABLE: MOM_MEETING
ALTER TABLE "MOM_MEETING" ADD  PRIMARY KEY ("MEETING_ID") ;

-- CHANGED TABLE: MOI_REQUEST_LOG
ALTER TABLE "MOI_REQUEST_LOG" ;

-- CHANGED TABLE: MOI_CITIZEN_DEPENDANTS
ALTER TABLE "MOI_CITIZEN_DEPENDANTS" ;

-- CHANGED TABLE: MOI_CITIZEN
ALTER TABLE "MOI_CITIZEN" ;

-- CHANGED TABLE: MOBILE_NOTIFICATIONS2
ALTER TABLE "MOBILE_NOTIFICATIONS2" MODIFY ("ID" NUMBER(10,0) DEFAULT "ISEQ$$_193658".nextval);

-- CHANGED TABLE: MOBILE_NOTIFICATIONS
ALTER TABLE "MOBILE_NOTIFICATIONS" DROP ("QUEUE_NAME");
ALTER TABLE "MOBILE_NOTIFICATIONS" MODIFY ("ID" NUMBER(10,0) DEFAULT "ISEQ$$_193783".nextval);
ALTER TABLE "MOBILE_NOTIFICATIONS" ADD  PRIMARY KEY ("ID") ENABLE;

-- CHANGED TABLE: MOBILE_FLAG2
ALTER TABLE "MOBILE_FLAG2" MODIFY ("ID" NUMBER DEFAULT "ISEQ$$_193759".nextval);

-- CHANGED TABLE: MOBILE_FLAG
ALTER TABLE "MOBILE_FLAG" MODIFY ("ID" NUMBER DEFAULT "ISEQ$$_193684".nextval);
ALTER TABLE "MOBILE_FLAG" ADD  PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "MOBILE_FLAG" ;

-- CHANGED TABLE: MOAMALAT_WORKFLOW_HISTORY2
ALTER TABLE "MOAMALAT_WORKFLOW_HISTORY2" ADD ("PROCEDURE" NUMBER(10,0));
ALTER TABLE "MOAMALAT_WORKFLOW_HISTORY2" DROP ("procedure");
ALTER TABLE "MOAMALAT_WORKFLOW_HISTORY2" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193740".nextval);

-- CHANGED TABLE: MOAMALAT_WORKFLOW2
ALTER TABLE "MOAMALAT_WORKFLOW2" ADD ("PROCEDURE" NUMBER(10,0));
ALTER TABLE "MOAMALAT_WORKFLOW2" DROP ("procedure");
ALTER TABLE "MOAMALAT_WORKFLOW2" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193620".nextval);

-- CHANGED TABLE: MOAMALAT_SERVICES_OPS
ALTER TABLE "MOAMALAT_SERVICES_OPS" ;

-- CHANGED TABLE: MOAMALAT_SERVICES_LOG
ALTER TABLE "MOAMALAT_SERVICES_LOG" STORAGE ( NEXT 1048576)  ;

-- CHANGED TABLE: MOAMALAT_SERVICES
ALTER TABLE "MOAMALAT_SERVICES" ;

-- CHANGED TABLE: MOAMALAT_INTEGRATION_DOCUMENTS
ALTER TABLE "MOAMALAT_INTEGRATION_DOCUMENTS" ;

-- CHANGED TABLE: MOAMALAH
ALTER TABLE "MOAMALAH" MODIFY ("ID" NUMBER DEFAULT "ISEQ$$_193695".nextval);
ALTER TABLE "MOAMALAH" ADD  PRIMARY KEY ("ID") ;
ALTER TABLE "MOAMALAH" ADD CONSTRAINT "UK_MOAMALAH_UNQ" UNIQUE ("CORRESPONDENCE_NUMBER","HIJRI_YEAR","TYPE_ID") ;

-- CHANGED TABLE: MENTION_PERMISSIONS
ALTER TABLE "MENTION_PERMISSIONS" ADD  PRIMARY KEY ("CODE") ENABLE;

-- CHANGED TABLE: LOV_COUNTRY
ALTER TABLE "LOV_COUNTRY" MODIFY ("CODE" NULL);
ALTER TABLE "LOV_COUNTRY" MODIFY ("LAST_UPDATED" TIMESTAMP(6) DEFAULT SYSTIMESTAMP);

-- CHANGED TABLE: LOV_CITY
ALTER TABLE "LOV_CITY" MODIFY ("CODE" NULL);
ALTER TABLE "LOV_CITY" MODIFY ("LAST_UPDATED" TIMESTAMP(6) DEFAULT SYSTIMESTAMP);

-- CHANGED TABLE: IO_WORKLOAD_BALANCER
ALTER TABLE "IO_WORKLOAD_BALANCER" ;

-- CHANGED TABLE: IO_USER_FAVOURITES
ALTER TABLE "IO_USER_FAVOURITES" ;

-- CHANGED TABLE: IO_USERCOMMENTS
ALTER TABLE "IO_USERCOMMENTS" ;

-- CHANGED TABLE: IO_USERACCESS
ALTER TABLE "IO_USERACCESS" ;

-- CHANGED TABLE: IO_TYPES
ALTER TABLE "IO_TYPES" ;

-- CHANGED TABLE: IO_TEST
ALTER TABLE "IO_TEST" ;

-- CHANGED TABLE: IO_SUBJECTS
ALTER TABLE "IO_SUBJECTS" ;

-- CHANGED TABLE: IO_SUBJECTCHANGELOG
ALTER TABLE "IO_SUBJECTCHANGELOG" ;

-- CHANGED TABLE: IO_SIGNATURES_BK20140810
ALTER TABLE "IO_SIGNATURES_BK20140810" ;

-- CHANGED TABLE: IO_SIGNATURES
ALTER TABLE "IO_SIGNATURES" ;

-- CHANGED TABLE: IO_SIGNABLE_SIGNERS
ALTER TABLE "IO_SIGNABLE_SIGNERS" ;

-- CHANGED TABLE: IO_SIGNABLE_CC
ALTER TABLE "IO_SIGNABLE_CC" ;

-- CHANGED TABLE: IO_SEQUENCENUMBERS
ALTER TABLE "IO_SEQUENCENUMBERS" ;

-- CHANGED TABLE: IO_SECTORS
ALTER TABLE "IO_SECTORS" ;

-- CHANGED TABLE: IO_REPORTPERMISSION
ALTER TABLE "IO_REPORTPERMISSION" ;

-- CHANGED TABLE: IO_REMINDER_SCHEDULE
ALTER TABLE "IO_REMINDER_SCHEDULE" ADD  PRIMARY KEY ("ID") ENABLE;

-- CHANGED TABLE: IO_RELATIONTYPE
ALTER TABLE "IO_RELATIONTYPE" ;

-- CHANGED TABLE: IO_RELATIONS
ALTER TABLE "IO_RELATIONS" ;

-- CHANGED TABLE: IO_REJECTIONREASONS
ALTER TABLE "IO_REJECTIONREASONS" ;

-- CHANGED TABLE: IO_RECEIVEMODES
ALTER TABLE "IO_RECEIVEMODES" ;

-- CHANGED TABLE: IO_REASONS
DROP TABLE "IO_REASONS";
  CREATE TABLE "IO_REASONS" 
   (	"REASONID" NUMBER NOT NULL ENABLE,
	"REASONDESC" VARCHAR2(100)
   );

-- CHANGED TABLE: IO_PREDEFINEDINSTRUCTIONS
ALTER TABLE "IO_PREDEFINEDINSTRUCTIONS" ;

-- CHANGED TABLE: IO_PERMISSIONTYPES
ALTER TABLE "IO_PERMISSIONTYPES" ;

-- CHANGED TABLE: IO_PACKAGETYPES
ALTER TABLE "IO_PACKAGETYPES" ;

-- CHANGED TABLE: IO_OUTGONINGDELIVERYREPORTTYPE
DROP TABLE "IO_OUTGONINGDELIVERYREPORTTYPE";
  CREATE TABLE "IO_OUTGONINGDELIVERYREPORTTYPE" 
   (	"REPORTID" NUMBER NOT NULL ENABLE,
	"DELIVERYREPORTDESC" VARCHAR2(50)
   );

-- CHANGED TABLE: IO_LETTERTYPES
ALTER TABLE "IO_LETTERTYPES" ;

-- CHANGED TABLE: IO_INTERNAL_DR_ITEMS
ALTER TABLE "IO_INTERNAL_DR_ITEMS" ;

-- CHANGED TABLE: IO_INTERNAL_DELIVERY_REPORTS
ALTER TABLE "IO_INTERNAL_DELIVERY_REPORTS" ;

-- CHANGED TABLE: IO_INTERNALDESTINATIONS
ALTER TABLE "IO_INTERNALDESTINATIONS" ;

-- CHANGED TABLE: IO_INTERNAL2023
ALTER TABLE "IO_INTERNAL2023" ADD ("SYSTEMTYPE" NUMBER);
ALTER TABLE "IO_INTERNAL2023" ;

-- CHANGED TABLE: IO_INSTRUCTIONSSECURITY
ALTER TABLE "IO_INSTRUCTIONSSECURITY" ;

-- CHANGED TABLE: IO_INCOMING_DR_TITEMS
ALTER TABLE "IO_INCOMING_DR_TITEMS" ;

-- CHANGED TABLE: IO_INCOMING_DELIVERYREPORT
ALTER TABLE "IO_INCOMING_DELIVERYREPORT" ;

-- CHANGED TABLE: IO_INCOMING_CLONES
ALTER TABLE "IO_INCOMING_CLONES" ;

-- CHANGED TABLE: IO_INCOMINGDESTINATIONS
ALTER TABLE "IO_INCOMINGDESTINATIONS" ;

-- CHANGED TABLE: IO_FORWARDINGDETAILS_BAK
ALTER TABLE "IO_FORWARDINGDETAILS_BAK" STORAGE ( NEXT 1048576)  ;

-- CHANGED TABLE: IO_FORWARDINGDETAILS
ALTER TABLE "IO_FORWARDINGDETAILS" STORAGE ( NEXT 1048576)  ;

-- CHANGED TABLE: IO_EXTERNALUNITS_BAK
ALTER TABLE "IO_EXTERNALUNITS_BAK" ;

-- CHANGED TABLE: IO_EXTERNALUNITS
DROP TABLE "IO_EXTERNALUNITS";
  CREATE TABLE "IO_EXTERNALUNITS" 
   (	"EXTERNALUNITID" NUMBER NOT NULL ENABLE,
	"EXTERNALUNITDESC" VARCHAR2(400) NOT NULL ENABLE,
	"EXTERNALUNITTYPE" NUMBER DEFAULT -1 NOT NULL ENABLE,
	"MOCODE" NUMBER NOT NULL ENABLE,
	"ORG_CODE" VARCHAR2(20),
	"NCAR" NUMBER,
	"MURASALAT_MEMBER" NUMBER,
	"SUB_ID" NUMBER DEFAULT 000,
	"SYSTEMTYPE" NUMBER,
	CONSTRAINT "IO_EXTERNALUNITS_NEW_PK" PRIMARY KEY ("EXTERNALUNITID")
  )  ENABLE
   );

-- CHANGED TABLE: IO_ESIGNATURE
ALTER TABLE "IO_ESIGNATURE" ;

-- CHANGED TABLE: IO_EMPLOYEES_ORG
ALTER TABLE "IO_EMPLOYEES_ORG" ;

-- CHANGED TABLE: IO_EMPLOYEES_25JUN
ALTER TABLE "IO_EMPLOYEES_25JUN" ;

-- CHANGED TABLE: IO_EMPLOYEES_20230104
ALTER TABLE "IO_EMPLOYEES_20230104" ;

-- CHANGED TABLE: IO_EMPLOYEES_2
ALTER TABLE "IO_EMPLOYEES_2" ;

-- CHANGED TABLE: IO_EMPLOYEESCONFIGS_ORG
ALTER TABLE "IO_EMPLOYEESCONFIGS_ORG" ;

-- CHANGED TABLE: IO_EMPLOYEESCONFIGS_25JUN
ALTER TABLE "IO_EMPLOYEESCONFIGS_25JUN" ;

-- CHANGED TABLE: IO_EMPLOYEESCONFIGS_2
ALTER TABLE "IO_EMPLOYEESCONFIGS_2" ;

-- CHANGED TABLE: IO_EMPLOYEEBACKUP
ALTER TABLE "IO_EMPLOYEEBACKUP" ;

-- CHANGED TABLE: IO_ELIGIBLEFORWARDINGTOLIST
ALTER TABLE "IO_ELIGIBLEFORWARDINGTOLIST" ;

-- CHANGED TABLE: IO_EBS_ID_DEPARTMENT_ID_ORG
ALTER TABLE "IO_EBS_ID_DEPARTMENT_ID_ORG" ;

-- CHANGED TABLE: IO_EBS_ID_DEPARTMENT_ID_NEW
ALTER TABLE "IO_EBS_ID_DEPARTMENT_ID_NEW" ;

-- CHANGED TABLE: IO_EBS_ID_DEPARTMENT_ID_18_4_2022
ALTER TABLE "IO_EBS_ID_DEPARTMENT_ID_18_4_2022" ;

-- CHANGED TABLE: IO_EBS_ID_DEPARTMENT_ID
ALTER TABLE "IO_EBS_ID_DEPARTMENT_ID" ;

-- CHANGED TABLE: IO_DR_CARRIERS
ALTER TABLE "IO_DR_CARRIERS" ;

-- CHANGED TABLE: IO_DOCUMENTS_BLOCK_ACCESS_PERMISSIONS
ALTER TABLE "IO_DOCUMENTS_BLOCK_ACCESS_PERMISSIONS" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193705".nextval);

-- CHANGED TABLE: IO_DOCUMENTS_BLOCK_ACCESS
ALTER TABLE "IO_DOCUMENTS_BLOCK_ACCESS" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193708".nextval);

-- CHANGED TABLE: IO_DEPARTMENTS_ORG
ALTER TABLE "IO_DEPARTMENTS_ORG" ;

-- CHANGED TABLE: IO_DEPARTMENTS_BEFORE_PARENTDEPARTMENTID
ALTER TABLE "IO_DEPARTMENTS_BEFORE_PARENTDEPARTMENTID" ;

-- CHANGED TABLE: IO_DEPARTMENTS_25JUN
ALTER TABLE "IO_DEPARTMENTS_25JUN" ;

-- CHANGED TABLE: IO_DEPARTMENTS_2
ALTER TABLE "IO_DEPARTMENTS_2" ;

-- CHANGED TABLE: IO_DEPARTMENTSCONFIGS_ORG
ALTER TABLE "IO_DEPARTMENTSCONFIGS_ORG" ;

-- CHANGED TABLE: IO_DEPARTMENTSCONFIGS_25JUN
ALTER TABLE "IO_DEPARTMENTSCONFIGS_25JUN" ;

-- CHANGED TABLE: IO_DEPARTMENTSCONFIGS_2
ALTER TABLE "IO_DEPARTMENTSCONFIGS_2" ;

-- CHANGED TABLE: IO_DEPARTMENTSCONFIGS
ALTER TABLE "IO_DEPARTMENTSCONFIGS" ;

-- CHANGED TABLE: IO_DEPARTMENTS
DROP TABLE "IO_DEPARTMENTS";
  CREATE TABLE "IO_DEPARTMENTS" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE,
	"DEPARTMENTNAME" VARCHAR2(250),
	"MANAGERID" NUMBER,
	"REPRESENTATIVEID" NUMBER,
	"PARENTDEPARTMENTID" NUMBER,
	"DEPARTMENTLEVEL" NUMBER DEFAULT -1,
	"CANACCESSSYSTEM" NUMBER DEFAULT 1,
	"DEPARTMENTCODE" VARCHAR2(20) NOT NULL ENABLE,
	"ISACTIVE" NUMBER DEFAULT 1 NOT NULL ENABLE,
	"SYMBOL" VARCHAR2(3),
	"SECTOR_ID" NUMBER,
	"EBS_DEPARTMENT_ID" NUMBER,
	"ARCHIVE_PAGE_URL" VARCHAR2(200),
	"PENSION_COMM_DEPT" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CAN_ACCESS_SYSTEM" NUMBER(10,0),
	"DEPARTMENT_CODE" VARCHAR2(255 CHAR),
	"DEPARTMENT_ID" NUMBER(19,0),
	"DEPARTMENT_LEVEL" NUMBER(10,0),
	"DEPARTMENT_NAME" VARCHAR2(255 CHAR),
	"IS_ACTIVE" NUMBER(10,0),
	"MANAGER_ID" NUMBER(19,0),
	"PARENT_DEPARTMENT_ID" NUMBER(19,0),
	"REPRESENTATIVE_ID" NUMBER(19,0),
	"CREATE_CIVIL_PRINT_CORRESPONDENCES" NUMBER(10,0),
	"CREATE_INCOMING_CORRESPONDENCES" NUMBER(10,0),
	"CREATE_INTERNAL_CORRESPONDENCES" NUMBER(10,0),
	"CREATE_OUTGOING_CORRESPONDENCES" NUMBER(10,0),
	"EXPORT_CORRESPONDENCES" NUMBER(10,0),
	CONSTRAINT "IO_DEPARTMENTS_NEW_PK" PRIMARY KEY ("DEPARTMENTID")
  )  ENABLE,
	CONSTRAINT "IO_DEPARTMENTS_CODEUK" UNIQUE ("DEPARTMENTCODE")
  )  ENABLE
   );

-- CHANGED TABLE: IO_DEPARTMENTQUEUES_ORG
ALTER TABLE "IO_DEPARTMENTQUEUES_ORG" ;

-- CHANGED TABLE: IO_DEPARTMENTQUEUES_25JUN
ALTER TABLE "IO_DEPARTMENTQUEUES_25JUN" ;

-- CHANGED TABLE: IO_DEPARTMENTQUEUES_2
ALTER TABLE "IO_DEPARTMENTQUEUES_2" ;

-- CHANGED TABLE: IO_DEPARTMENTQUEUES
ALTER TABLE "IO_DEPARTMENTQUEUES" ;

-- CHANGED TABLE: IO_DELIVERYREPORTS_DOCIDS
ALTER TABLE "IO_DELIVERYREPORTS_DOCIDS" ;

-- CHANGED TABLE: IO_DELIVERYREPORTS
DROP TABLE "IO_DELIVERYREPORTS";
  CREATE TABLE "IO_DELIVERYREPORTS" 
   (	"DELIVERYREPORTID" NUMBER NOT NULL ENABLE,
	"REPORTHIJRICYEAR" NUMBER NOT NULL ENABLE,
	"PREPAREDBYDEPARTMENTID" NUMBER,
	"PACKAGETYPEID" NUMBER,
	"REPORTTYPE" NUMBER DEFAULT 1,
	"DATECREATED" NUMBER,
	"CREATEDBY" VARCHAR2(20),
	"DATEMODIFIED" NUMBER,
	"LASTMODIFIEDBY" VARCHAR2(20),
	"WASPRINTED" NUMBER DEFAULT 0,
	"DELIVERYREPORTTYPEID" NUMBER,
	"DELEVARYREPORTSTYLE" NUMBER,
	"ISREPORTCLOSED" NUMBER,
	"SHOWSECURESUBJECT" NUMBER,
	"COURIERID" VARCHAR2(40),
	"RECEIVEMODEID" NUMBER,
	"HANDDELIVERYPERSONNELID" VARCHAR2(20),
	"POSTOFFICEID" NUMBER,
	"OLDDELIVERYREPORTID" NUMBER,
	"OLDDELIVERYREPORTTYPE" NUMBER DEFAULT 0,
	"ISCREATORMINISTEREMPLOYEE" NUMBER,
	CONSTRAINT "IO_DELIVERYREPORTS_PK" PRIMARY KEY ("DELIVERYREPORTID","REPORTHIJRICYEAR")
  )  ENABLE
   );

-- CHANGED TABLE: IO_DELIVERYREPORTITEMS
ALTER TABLE "IO_DELIVERYREPORTITEMS" ;

-- CHANGED TABLE: IO_CORRESPONDENCETYPES
ALTER TABLE "IO_CORRESPONDENCETYPES" ;

-- CHANGED TABLE: IO_CORRESPONDENCESECURITY
ALTER TABLE "IO_CORRESPONDENCESECURITY" ;

-- CHANGED TABLE: IO_CORRESPONDENCEFOLLOWUP
ALTER TABLE "IO_CORRESPONDENCEFOLLOWUP" ;

-- CHANGED TABLE: IO_CORRESPONDENCECATEGORIES
ALTER TABLE "IO_CORRESPONDENCECATEGORIES" ;

-- CHANGED TABLE: IO_CONFIDENTIALITY
ALTER TABLE "IO_CONFIDENTIALITY" ;

-- CHANGED TABLE: IO_COMMITTEES
ALTER TABLE "IO_COMMITTEES" ;

-- CHANGED TABLE: IO_COMMITTEEMEMBERS
ALTER TABLE "IO_COMMITTEEMEMBERS" ;

-- CHANGED TABLE: IO_CIRCULAR_TYPES
ALTER TABLE "IO_CIRCULAR_TYPES" ;

-- CHANGED TABLE: IO_CIRCULAR_RELATIONS
ALTER TABLE "IO_CIRCULAR_RELATIONS" ;

-- CHANGED TABLE: IO_CIRCULARDESTINATIONS
ALTER TABLE "IO_CIRCULARDESTINATIONS" ;

-- CHANGED TABLE: IO_CIRCULAR
ALTER TABLE "IO_CIRCULAR" ;

-- CHANGED TABLE: IO_BANKS
ALTER TABLE "IO_BANKS" ;

-- CHANGED TABLE: IO_BACKUP_SIGNER
ALTER TABLE "IO_BACKUP_SIGNER" ;

-- CHANGED TABLE: IO_ATTCHMNT_ACCESS_REQ_STATUS
ALTER TABLE "IO_ATTCHMNT_ACCESS_REQ_STATUS" ;

-- CHANGED TABLE: IO_ATTCHMNT_ACCESS_REQ_LOG
ALTER TABLE "IO_ATTCHMNT_ACCESS_REQ_LOG" ;

-- CHANGED TABLE: IO_ATTCHMNT_ACCESS_ACTION_TYPE
ALTER TABLE "IO_ATTCHMNT_ACCESS_ACTION_TYPE" ;

-- CHANGED TABLE: IO_ATTACHMENT_ACCESS_REQUEST
ALTER TABLE "IO_ATTACHMENT_ACCESS_REQUEST" ;

-- CHANGED TABLE: IO_ANNOTATIONS_PERMISSION
ALTER TABLE "IO_ANNOTATIONS_PERMISSION" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193805".nextval);

-- CHANGED TABLE: IO_ANNOTATIONS
ALTER TABLE "IO_ANNOTATIONS" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193864".nextval);

-- CHANGED TABLE: IO_ACTION_LOG_ACTION_TYPES
ALTER TABLE "IO_ACTION_LOG_ACTION_TYPES" ;

-- CHANGED TABLE: IO_ACTION_LOG
ALTER TABLE "IO_ACTION_LOG" STORAGE ( NEXT 1048576)  ;

-- CHANGED TABLE: IO_ACTIONS
ALTER TABLE "IO_ACTIONS" ;

-- CHANGED TABLE: HTTPSESSION_LOG
ALTER TABLE "HTTPSESSION_LOG" STORAGE ( NEXT 1048576)  ;

-- CHANGED TABLE: FORM_TYPES
ALTER TABLE "FORM_TYPES" ;

-- CHANGED TABLE: FORMS_VPN_REQUEST
ALTER TABLE "FORMS_VPN_REQUEST" ;

-- CHANGED TABLE: FORMS_PARTICIPANTS_CONFIG
ALTER TABLE "FORMS_PARTICIPANTS_CONFIG" ;

-- CHANGED TABLE: FILE_CLASSIFICATION
ALTER TABLE "FILE_CLASSIFICATION" DROP ("ID");

-- CHANGED TABLE: FILE_ACCESS_REQUEST
ALTER TABLE "FILE_ACCESS_REQUEST" MODIFY ("CORRESPONDENCE_TYPE" NUMBER(2,0));
ALTER TABLE "FILE_ACCESS_REQUEST" MODIFY ("HIJRI_YEAR" NUMBER(4,0));
ALTER TABLE "FILE_ACCESS_REQUEST" MODIFY ("REQUEST_ID" NUMBER(19,0) DEFAULT "ISEQ$$_193718".nextval);

-- CHANGED TABLE: EMPLOYEESCONFIG
ALTER TABLE "EMPLOYEESCONFIG" ;

-- CHANGED TABLE: EMPLOYEES
ALTER TABLE "EMPLOYEES" ;

-- CHANGED TABLE: EMAIL_FAVORITES2
ALTER TABLE "EMAIL_FAVORITES2" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193627".nextval);

-- CHANGED TABLE: EMAIL_FAVORITES
ALTER TABLE "EMAIL_FAVORITES" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193852".nextval);
ALTER TABLE "EMAIL_FAVORITES" ADD  PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "EMAIL_FAVORITES" ;

-- CHANGED TABLE: DS_CALENDAR
ALTER TABLE "DS_CALENDAR" ;

-- CHANGED TABLE: CONVERSATION_USER
ALTER TABLE "CONVERSATION_USER" MODIFY ("ARCHIVED" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "CONVERSATION_USER" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193796".nextval);
ALTER TABLE "CONVERSATION_USER" MODIFY ("PINNED" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "CONVERSATION_USER" MODIFY ("REMOVED" NUMBER(1,0) DEFAULT 0);

-- CHANGED TABLE: CONVERSATION
ALTER TABLE "CONVERSATION" MODIFY ("CORRESPONDENCE_NUMBER" NOT NULL ENABLE);
ALTER TABLE "CONVERSATION" MODIFY ("CORRESPONDENCE_TYPE" NOT NULL ENABLE);
ALTER TABLE "CONVERSATION" MODIFY ("DELETED" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "CONVERSATION" MODIFY ("HIJRI_YEAR" NOT NULL ENABLE);
ALTER TABLE "CONVERSATION" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193838".nextval);

-- CHANGED TABLE: CONTACT_EXCEPTION
ALTER TABLE "CONTACT_EXCEPTION" MODIFY ("ID" NUMBER DEFAULT "ISEQ$$_193613".nextval);
ALTER TABLE "CONTACT_EXCEPTION" ;

-- CHANGED TABLE: BINDER_INFO
ALTER TABLE "BINDER_INFO" ;

-- CHANGED TABLE: BATCH_LOCATION
ALTER TABLE "BATCH_LOCATION" ;

-- CHANGED TABLE: ARCHIVE_PRODUCTIVITY_TARGET
DROP TABLE "ARCHIVE_PRODUCTIVITY_TARGET";
  CREATE TABLE "ARCHIVE_PRODUCTIVITY_TARGET" 
   (	"ID" NUMBER(19,0) DEFAULT "ISEQ$$_193855".nextval NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"EMPLOYEE_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"SET_BY" VARCHAR2(20 CHAR),
	"TARGET_PAGES" NUMBER(10,0) NOT NULL ENABLE,
	"TARGET_YEAR" NUMBER(10,0) NOT NULL ENABLE,
	PRIMARY KEY ("ID")
  ,
	CONSTRAINT "UKJE14WCW7RX2PROMX04M6HO8DR" UNIQUE ("EMPLOYEE_ID","TARGET_YEAR")
  );

-- CHANGED TABLE: ARCHIVE_MAPPINGS
ALTER TABLE "ARCHIVE_MAPPINGS" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193673".nextval);
ALTER TABLE "ARCHIVE_MAPPINGS" ADD CONSTRAINT "UKIAD9GA0T7ABP829NS5B0VYO7Q" UNIQUE ("DEPARTMENT_ID") ;

-- CHANGED TABLE: ARCHIVE_KNOWLEDGE_DOC
ALTER TABLE "ARCHIVE_KNOWLEDGE_DOC" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193869".nextval);

-- CHANGED TABLE: ARCHIVE_INCOMING_SEQUENCE_CONFIDENTIAL
ALTER TABLE "ARCHIVE_INCOMING_SEQUENCE_CONFIDENTIAL" ;

-- CHANGED TABLE: ARCHIVE_INCOMING_SEQUENCE
ALTER TABLE "ARCHIVE_INCOMING_SEQUENCE" ;

-- CHANGED TABLE: ARCHIVE_INCOMING_PENSION_INTEG
ALTER TABLE "ARCHIVE_INCOMING_PENSION_INTEG" DROP ("DESCRIPTION");
ALTER TABLE "ARCHIVE_INCOMING_PENSION_INTEG" ;

-- CHANGED TABLE: ARCHIVE_INCOMING_PENSION_COMM
ALTER TABLE "ARCHIVE_INCOMING_PENSION_COMM" ;

-- CHANGED TABLE: ARCHIVE_INCOMING
ALTER TABLE "ARCHIVE_INCOMING" ;

-- CHANGED TABLE: ARCHIVE_FIELD_OPTIONS
DROP TABLE "ARCHIVE_FIELD_OPTIONS";
  CREATE TABLE "ARCHIVE_FIELD_OPTIONS" 
   (	"ID" NUMBER(19,0) DEFAULT "ISEQ$$_193621".nextval NOT NULL ENABLE,
	"ACTIVE" NUMBER(1,0),
	"VALUE_AR" VARCHAR2(200 CHAR),
	"VALUE_EN" VARCHAR2(200 CHAR) NOT NULL ENABLE,
	"FIELD_ID" NUMBER(19,0) NOT NULL ENABLE,
	CHECK (active in (0,1)) ENABLE,
	PRIMARY KEY ("ID")
  )  ENABLE,
	CONSTRAINT "UKFR0VW4UML3M68UI3ICAIEM7A5" UNIQUE ("FIELD_ID","VALUE_EN")
  )  ENABLE,
	CONSTRAINT "FK7IUAYFCFQSPCP8EW25BSFE1K9" FOREIGN KEY ("FIELD_ID")
	 REFERENCES "ARCHIVE_FIELDS" ("ID") ENABLE
   );

-- CHANGED TABLE: ARCHIVE_FIELDS
DROP TABLE "ARCHIVE_FIELDS";
  CREATE TABLE "ARCHIVE_FIELDS" 
   (	"ID" NUMBER(19,0) DEFAULT "ISEQ$$_193676".nextval NOT NULL ENABLE,
	"ACTIVE" NUMBER(1,0),
	"ARABIC_NAME" VARCHAR2(200 CHAR),
	"DATA_TYPE" VARCHAR2(50 CHAR),
	"DEFAULT_VALUE" VARCHAR2(2000 CHAR),
	"DESCRIPTION" VARCHAR2(100 CHAR),
	"DISPLAY_ORDER" NUMBER(10,0),
	"DISPLAY_TYPE" VARCHAR2(50 CHAR),
	"FROM_DATE" DATE,
	"HELP_TEXT" VARCHAR2(500 CHAR),
	"MAX_CHARS" NUMBER(10,0),
	"MIN_CHARS" NUMBER(10,0),
	"NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,
	"REPORTABLE" NUMBER(1,0),
	"IS_REQUIRED" NUMBER(1,0),
	"SELECTION_MODE" VARCHAR2(20 CHAR),
	"TO_DATE" DATE,
	"DEPARTMENT_ID" NUMBER(19,0) NOT NULL ENABLE,
	"HELP_TEXT_AR" VARCHAR2(500 CHAR),
	CHECK (display_type in ('RADIO_BUTTON','TEXT_AREA','CHECKBOX','TEXT_FIELD','DROPDOWN_MENU','DATE_PICKER','DATE_TIME_PICKER')) ENABLE,
	CHECK (selection_mode in ('SINGLE_SELECT','MULTI_SELECT')) ENABLE,
	CHECK (is_required in (0,1)) ENABLE,
	CHECK (data_type in ('STRING','INTEGER','DOUBLE','BOOLEAN','DATE','JSON','LONG')) ENABLE,
	CHECK (reportable in (0,1)) ENABLE,
	CHECK (active in (0,1)) ENABLE,
	PRIMARY KEY ("ID")
  )  ENABLE,
	CONSTRAINT "UKJHFR0HI8VAQ0J4HILXISD23S2" UNIQUE ("DEPARTMENT_ID","NAME")
  )  ENABLE,
	CONSTRAINT "FK7BSM1FJY7QUSA4LE9YLBTXS1S" FOREIGN KEY ("DEPARTMENT_ID")
	 REFERENCES "ARCHIVE_DEPARTMENT" ("ID") ENABLE
   );

-- CHANGED TABLE: ARCHIVE_ACTIVITY
DROP TABLE "ARCHIVE_ACTIVITY";
  CREATE TABLE "ARCHIVE_ACTIVITY" 
   (	"ID" NUMBER(19,0) DEFAULT "ISEQ$$_193845".nextval NOT NULL ENABLE,
	"ACTION_DATE" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
	"ACTION_TYPE" VARCHAR2(20 CHAR),
	"DEPARTMENT_ID" NUMBER(19,0),
	"DOCUMENT_TITLE" VARCHAR2(500 CHAR),
	"EMPLOYEE_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"PAGE_COUNT" NUMBER(10,0),
	PRIMARY KEY ("ID")
  );

-- CHANGED TABLE: AD_PHOTO
ALTER TABLE "AD_PHOTO" ADD  PRIMARY KEY ("USERID") ENABLE;
