-- ==================================================================
--  [03b] CHANGED TABLES — ⚠️  REVIEW REQUIRED  (24)
--  DROP / MODIFY statements — review carefully before running
--  Target schema : MOAMALAT
--  Run as        : DBA or MOAMALAT user
-- ==================================================================

-- ⚠️  IMPORTANT:
--   Lines with DROP CONSTRAINT / DROP PRIMARY KEY / DROP COLUMN are commented out.
--   For MODIFY (type change): run 00_precheck_type_changes.sql first.
--   For DROP CONSTRAINT / DROP PRIMARY KEY: verify no FK dependencies exist.
--   ALTER TABLE ... MOVE lines have been REMOVED entirely (storage-only, breaks indexes).
--   Uncomment only after confirming it is safe.

-- ⚠️  TABLE: WORKFLOW_WORKITEMS
ALTER TABLE "WORKFLOW_WORKITEMS" ADD ("HIJRIYEAR" NUMBER(10,0));
ALTER TABLE "WORKFLOW_WORKITEMS" MODIFY ("F_LOCKUSER" VARCHAR2(200 CHAR));
ALTER TABLE "WORKFLOW_WORKITEMS" MODIFY ("IS_RECALLED" NUMBER(10,0) DEFAULT 0);
-- ⚠️  ALTER TABLE "WORKFLOW_WORKITEMS" DROP PRIMARY KEY;

-- ⚠️  TABLE: WF_QUEUE_USERS
ALTER TABLE "WF_QUEUE_USERS" MODIFY ("ACTIVE" NOT NULL ENABLE);
ALTER TABLE "WF_QUEUE_USERS" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193721".nextval);
-- ⚠️  ALTER TABLE "WF_QUEUE_USERS" DROP CONSTRAINT "WF_QUEUE_USERS_UK";
ALTER TABLE "WF_QUEUE_USERS" ADD CONSTRAINT "UK61L8UYCX7YYKRS2GJUVBCMYUU" UNIQUE ("QUEUE_NAME","USERNAME") ENABLE;

-- ⚠️  TABLE: MOAMALAT_PERMISSION_ASSIGNMENTS
ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" MODIFY ("ACTIVE" NUMBER(1,0) DEFAULT 1);
ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" MODIFY ("DATE_ADDED" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" MODIFY ("DATE_UPDATED" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" MODIFY ("ENTITY_ID" VARCHAR2(50));
ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" MODIFY ("ENTITY_TYPE" VARCHAR2(20));
ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" MODIFY ("ID" NUMBER DEFAULT "ISEQ$$_193650".nextval);
ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" MODIFY ("PERMISSION_CODE" NUMBER);
-- ⚠️  ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" DROP PRIMARY KEY;
-- ⚠️  ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" DROP CONSTRAINT "FK29ED2X7HLHD4HKIFWEX3BRW3";
ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" ADD CONSTRAINT "PK_MOAMALAT_PERMISSION_ASSIGN" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "MOAMALAT_PERMISSION_ASSIGNMENTS" ADD CONSTRAINT "FK_MOAMALAT_PERMISSION_ASSIGN_CODE" FOREIGN KEY ("PERMISSION_CODE") REFERENCES "MOAMALAT_PERMISSIONS"("PERMISSION_CODE") ENABLE;

-- ⚠️  TABLE: MOAMALAT_PERMISSIONS
ALTER TABLE "MOAMALAT_PERMISSIONS" DROP ("SYSTEM");
ALTER TABLE "MOAMALAT_PERMISSIONS" MODIFY ("ACTIVE" NUMBER(1,0) DEFAULT 1);
ALTER TABLE "MOAMALAT_PERMISSIONS" MODIFY ("DATE_ADDED" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "MOAMALAT_PERMISSIONS" MODIFY ("DATE_UPDATED" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "MOAMALAT_PERMISSIONS" MODIFY ("ID" NUMBER DEFAULT "ISEQ$$_193810".nextval);
ALTER TABLE "MOAMALAT_PERMISSIONS" MODIFY ("NAME_AR" VARCHAR2(200));
ALTER TABLE "MOAMALAT_PERMISSIONS" MODIFY ("NAME_EN" VARCHAR2(200));
ALTER TABLE "MOAMALAT_PERMISSIONS" MODIFY ("PERMISSION_CODE" NUMBER);
-- ⚠️  ALTER TABLE "MOAMALAT_PERMISSIONS" DROP PRIMARY KEY;
-- ⚠️  ALTER TABLE "MOAMALAT_PERMISSIONS" DROP CONSTRAINT "UK_Q4CQVT27OT0N2862AQAGE7R8V";
ALTER TABLE "MOAMALAT_PERMISSIONS" ADD CONSTRAINT "PK_MOAMALAT_PERMISSIONS" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "MOAMALAT_PERMISSIONS" ADD CONSTRAINT "UQ_MOAMALAT_PERMISSIONS_CODE" UNIQUE ("PERMISSION_CODE") ENABLE;

-- ⚠️  TABLE: IO_REMINDNOTIF
ALTER TABLE "IO_REMINDNOTIF" MODIFY ("RECEIVERID" VARCHAR2(400));
ALTER TABLE "IO_REMINDNOTIF" MODIFY ("SENDERID" VARCHAR2(400));
ALTER TABLE "IO_REMINDNOTIF" ;

-- ⚠️  TABLE: IO_REMINDERS
ALTER TABLE "IO_REMINDERS" MODIFY ("CREATED_AT" TIMESTAMP(6) DEFAULT SYSDATE);
ALTER TABLE "IO_REMINDERS" MODIFY ("DEADLINE_AT" NULL);
ALTER TABLE "IO_REMINDERS" MODIFY ("ESCALATION_DONE_FLAG" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "IO_REMINDERS" MODIFY ("ESCALATION_ENABLED" NUMBER(1,0));
ALTER TABLE "IO_REMINDERS" MODIFY ("ESCALATION_EXTENDED_FLAG" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "IO_REMINDERS" MODIFY ("ESCALATION_MODE" NUMBER(1,0));
ALTER TABLE "IO_REMINDERS" MODIFY ("HIJRICYEAR" NUMBER(4,0));
ALTER TABLE "IO_REMINDERS" MODIFY ("IS_ACTIVE" NUMBER(1,0) DEFAULT 1);
ALTER TABLE "IO_REMINDERS" MODIFY ("REM1_SENT_FLAG" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "IO_REMINDERS" MODIFY ("REM2_SENT_FLAG" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "IO_REMINDERS" MODIFY ("REM3_SENT_FLAG" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "IO_REMINDERS" MODIFY ("REMINDER_COUNT" NUMBER(1,0));
ALTER TABLE "IO_REMINDERS" MODIFY ("REMINDER_COUNT" NULL);
ALTER TABLE "IO_REMINDERS" MODIFY ("RESOLVED_FLAG" NUMBER(1,0) DEFAULT 0);
-- ⚠️  ALTER TABLE "IO_REMINDERS" DROP PRIMARY KEY;
ALTER TABLE "IO_REMINDERS" ADD CONSTRAINT "PK_IO_REMINDERS" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "IO_REMINDERS" ADD CONSTRAINT "UK_IO_REM_SCHED" UNIQUE ("CORRESPONDENCENUMBER","HIJRICYEAR","TYPEID","USER_ID") ENABLE;

-- ⚠️  TABLE: IO_REMINDER
ALTER TABLE "IO_REMINDER" ADD ("TEST" NUMBER);
ALTER TABLE "IO_REMINDER" MODIFY ("MESSAGE_CONTENT" VARCHAR2(1000));
ALTER TABLE "IO_REMINDER" MODIFY ("REMINDERTO" VARCHAR2(1500));
ALTER TABLE "IO_REMINDER" MODIFY ("SUBJECT" VARCHAR2(500));
ALTER TABLE "IO_REMINDER" ;

-- ⚠️  TABLE: IO_OUTGOINGDESTINATIONS
ALTER TABLE "IO_OUTGOINGDESTINATIONS" MODIFY ("NATIONALADDRESS" VARCHAR2(2000));
ALTER TABLE "IO_OUTGOINGDESTINATIONS" ;

-- ⚠️  TABLE: IO_OUTGOING
ALTER TABLE "IO_OUTGOING" MODIFY ("REMARKS" VARCHAR2(1000));
ALTER TABLE "IO_OUTGOING" STORAGE ( NEXT 1048576)  ;

-- ⚠️  TABLE: IO_MULTI_USER_INSTRUCTIONS
ALTER TABLE "IO_MULTI_USER_INSTRUCTIONS" MODIFY ("PROCEDURE" VARCHAR2(100));
ALTER TABLE "IO_MULTI_USER_INSTRUCTIONS" STORAGE ( NEXT 1048576)  ;

-- ⚠️  TABLE: IO_INTERNAL
ALTER TABLE "IO_INTERNAL" MODIFY ("CORRESPONDENCEATTACHMENTS" VARCHAR2(200));
ALTER TABLE "IO_INTERNAL" MODIFY ("REMARKS" VARCHAR2(1000));
ALTER TABLE "IO_INTERNAL" ;

-- ⚠️  TABLE: IO_INCOMING
ALTER TABLE "IO_INCOMING" MODIFY CONSTRAINT "FK_IO_INCOMING_IO_RECEIVEMODES" DISABLE NOVALIDATE;
ALTER TABLE "IO_INCOMING" STORAGE ( NEXT 1048576)  ;

-- ⚠️  TABLE: IO_FORWARDINGSHISTORY
ALTER TABLE "IO_FORWARDINGSHISTORY" MODIFY ("INSTRUCTIONS" VARCHAR2(4000));
ALTER TABLE "IO_FORWARDINGSHISTORY" STORAGE ( NEXT 1048576)  ;

-- ⚠️  TABLE: IO_EMPLOYEESCONFIGS
ALTER TABLE "IO_EMPLOYEESCONFIGS" MODIFY ("SYSTEMTYPE" VARCHAR2(20) DEFAULT 0);
-- ⚠️  ALTER TABLE "IO_EMPLOYEESCONFIGS" DROP CONSTRAINT "IO_EMPLOYEESCONFIGS_NEW_PK";
ALTER TABLE "IO_EMPLOYEESCONFIGS" ;

-- ⚠️  TABLE: IO_EMPLOYEES
-- ⚠️  ALTER TABLE "IO_EMPLOYEES" DROP CONSTRAINT "IO_EMPLOYEES_NEW_PK";
-- ⚠️  ALTER TABLE "IO_EMPLOYEES" DROP CONSTRAINT "IO_EMPLOYEES_UK1";
-- ⚠️  ALTER TABLE "IO_EMPLOYEES" DROP CONSTRAINT "IO_EMPLOYEES_UK2";
ALTER TABLE "IO_EMPLOYEES" ;

-- ⚠️  TABLE: FILE_ACCESS
ALTER TABLE "FILE_ACCESS" ADD ("ASSIGNED_BY" VARCHAR2(255 CHAR));
ALTER TABLE "FILE_ACCESS" MODIFY ("CORRESPONDENCE_TYPE" NUMBER(2,0));
ALTER TABLE "FILE_ACCESS" MODIFY ("HIJRI_YEAR" NUMBER(4,0));

-- ⚠️  TABLE: EMPLOYEE_DELEGATION
ALTER TABLE "EMPLOYEE_DELEGATION" MODIFY ("ID" NUMBER DEFAULT "ISEQ$$_193753".nextval);
-- ⚠️  ALTER TABLE "EMPLOYEE_DELEGATION" DROP CONSTRAINT "EMPLOYEE_DELEGATION_PK";
ALTER TABLE "EMPLOYEE_DELEGATION" ADD  PRIMARY KEY ("ID") ENABLE;

-- ⚠️  TABLE: CONVERSATION_COMMENT_READ
ALTER TABLE "CONVERSATION_COMMENT_READ" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193602".nextval);
-- ⚠️  ALTER TABLE "CONVERSATION_COMMENT_READ" DROP CONSTRAINT "FKGSG9XCWIJ7R15EU79LWX32HAF";
ALTER TABLE "CONVERSATION_COMMENT_READ" ADD CONSTRAINT "FK_COMMENT_READ_COMMENT" FOREIGN KEY ("COMMENT_ID") REFERENCES "CONVERSATION_COMMENT"("ID") ENABLE;

-- ⚠️  TABLE: CONVERSATION_COMMENT
ALTER TABLE "CONVERSATION_COMMENT" MODIFY ("DELETED" NUMBER(1,0) DEFAULT 0);
ALTER TABLE "CONVERSATION_COMMENT" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193905".nextval);
ALTER TABLE "CONVERSATION_COMMENT" MODIFY ("IS_SYSTEM_MESSAGE" NUMBER(1,0) DEFAULT 0);
-- ⚠️  ALTER TABLE "CONVERSATION_COMMENT" DROP CONSTRAINT "FK3GDHXJ4Y2VKJ4JA69NV9GD9NR";
ALTER TABLE "CONVERSATION_COMMENT" ADD CONSTRAINT "FK_CONV_COMMENT_CONV" FOREIGN KEY ("CONVERSATION_ID") REFERENCES "CONVERSATION"("ID") ENABLE;

-- ⚠️  TABLE: ARCHIVE_SEARCH_FIELD_CONFIG
ALTER TABLE "ARCHIVE_SEARCH_FIELD_CONFIG" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193848".nextval);
-- ⚠️  ALTER TABLE "ARCHIVE_SEARCH_FIELD_CONFIG" DROP CONSTRAINT SYS_C00119608;
-- ⚠️  ALTER TABLE "ARCHIVE_SEARCH_FIELD_CONFIG" DROP CONSTRAINT SYS_C00119609;
-- ⚠️  ALTER TABLE "ARCHIVE_SEARCH_FIELD_CONFIG" DROP CONSTRAINT SYS_C00119610;
ALTER TABLE "ARCHIVE_SEARCH_FIELD_CONFIG" ADD  CHECK (visible in (0,1)) ENABLE;
ALTER TABLE "ARCHIVE_SEARCH_FIELD_CONFIG" ADD  CHECK (mandatory in (0,1)) ENABLE;
ALTER TABLE "ARCHIVE_SEARCH_FIELD_CONFIG" ADD  CHECK (active in (0,1)) ENABLE;

-- ⚠️  TABLE: ARCHIVE_SEARCH_CONFIG
ALTER TABLE "ARCHIVE_SEARCH_CONFIG" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193841".nextval);
-- ⚠️  ALTER TABLE "ARCHIVE_SEARCH_CONFIG" DROP CONSTRAINT SYS_C00119604;
ALTER TABLE "ARCHIVE_SEARCH_CONFIG" ADD  CHECK (active in (0,1)) ENABLE;

-- ⚠️  TABLE: ARCHIVE_RULE
ALTER TABLE "ARCHIVE_RULE" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193744".nextval);
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "PK_ARCHIVE_RULE";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "FK_ARCHIVE_RULE_DEPT";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "FK_ARCHIVE_RULE_FIELD";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "FK_ARCHIVE_RULE_TARGET_FIELD";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "UK_ARCHIVE_RULE_DEPT_FIELD";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "CHK_ARCHIVE_RULE_NOT_SELF";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "CHK_ARCHIVE_RULE_OPERATOR";
ALTER TABLE "ARCHIVE_RULE" ADD  PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "ARCHIVE_RULE" ADD CONSTRAINT "FK5536X2WFP92LFPU6CFLDV2YTD" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "ARCHIVE_DEPARTMENT"("ID") ENABLE;
ALTER TABLE "ARCHIVE_RULE" ADD CONSTRAINT "FKFNQIH76KL2034B5MHS46OS1IC" FOREIGN KEY ("FIELD_ID") REFERENCES "ARCHIVE_FIELDS"("ID") ENABLE;
ALTER TABLE "ARCHIVE_RULE" ADD CONSTRAINT "FKMHAU5YIOS85WBJSWVGALI2G1P" FOREIGN KEY ("TARGET_FIELD_ID") REFERENCES "ARCHIVE_FIELDS"("ID") ENABLE;
ALTER TABLE "ARCHIVE_RULE" ADD  CHECK (operator in ('EQUALS','NOT_EQUALS','CONTAINS','STARTS_WITH')) ENABLE;
ALTER TABLE "ARCHIVE_RULE" ;

-- ⚠️  TABLE: ARCHIVE_FIELD_MAPPINGS
ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193634".nextval);
-- ⚠️  ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" DROP CONSTRAINT "PK_ARCHIVE_FIELD_MAPPINGS";
-- ⚠️  ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" DROP CONSTRAINT "FK_AFM_DEPT";
-- ⚠️  ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" DROP CONSTRAINT "UK_ARCHIVE_FIELD_MAPPINGS";
ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" ADD  PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" ADD CONSTRAINT "FK45YO76DVO9B7TILESTJ3N1FBS" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "ARCHIVE_DEPARTMENT"("ID") ENABLE;
ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" ADD CONSTRAINT "UKMCDK0ETTSUT0JGS0PTQYYNBVC" UNIQUE ("DEPARTMENT_ID","FIELD_ID","FILENET_CLASS") ENABLE;
ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" ;

-- ⚠️  TABLE: ARCHIVE_DEPARTMENT
ALTER TABLE "ARCHIVE_DEPARTMENT" DROP ("ACTIVE");
ALTER TABLE "ARCHIVE_DEPARTMENT" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193830".nextval);
-- ⚠️  ALTER TABLE "ARCHIVE_DEPARTMENT" DROP CONSTRAINT "PK_ARCHIVE_DEPARTMENT";
-- ⚠️  ALTER TABLE "ARCHIVE_DEPARTMENT" DROP CONSTRAINT "UK_ARCHIVE_DEPARTMENT_CODE";
ALTER TABLE "ARCHIVE_DEPARTMENT" ADD  PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "ARCHIVE_DEPARTMENT" ADD CONSTRAINT "UKSPV2PJ23CP8GDBH0AEUXTTDYA" UNIQUE ("CODE") ENABLE;
ALTER TABLE "ARCHIVE_DEPARTMENT" ;
