-- ==================================================================
--  [03b-LEGACY] OLD / EXISTING TABLES — ⚠️  STILL NEEDS REVIEW  (13)
--  These are pre-existing production tables. DROP CONSTRAINT and
--  DROP PRIMARY KEY remain commented out — verify FK dependencies
--  and data impact before uncommenting.
--  Target schema : MOAMALAT
--  Run as        : DBA or MOAMALAT user
-- ==================================================================

-- ⚠️  TABLE: IO_REMINDNOTIF
ALTER TABLE "IO_REMINDNOTIF" MODIFY ("RECEIVERID" VARCHAR2(400));
ALTER TABLE "IO_REMINDNOTIF" MODIFY ("SENDERID" VARCHAR2(400));

-- ⚠️  TABLE: IO_REMINDER
ALTER TABLE "IO_REMINDER" ADD ("TEST" NUMBER);
ALTER TABLE "IO_REMINDER" MODIFY ("MESSAGE_CONTENT" VARCHAR2(1000));
ALTER TABLE "IO_REMINDER" MODIFY ("REMINDERTO" VARCHAR2(1500));
ALTER TABLE "IO_REMINDER" MODIFY ("SUBJECT" VARCHAR2(500));

-- ⚠️  TABLE: IO_OUTGOINGDESTINATIONS
ALTER TABLE "IO_OUTGOINGDESTINATIONS" MODIFY ("NATIONALADDRESS" VARCHAR2(2000));

-- ⚠️  TABLE: IO_OUTGOING
ALTER TABLE "IO_OUTGOING" MODIFY ("REMARKS" VARCHAR2(1000));
ALTER TABLE "IO_OUTGOING" STORAGE ( NEXT 1048576)  ;

-- ⚠️  TABLE: IO_MULTI_USER_INSTRUCTIONS
ALTER TABLE "IO_MULTI_USER_INSTRUCTIONS" MODIFY ("PROCEDURE" VARCHAR2(100));
ALTER TABLE "IO_MULTI_USER_INSTRUCTIONS" STORAGE ( NEXT 1048576)  ;

-- ⚠️  TABLE: IO_INTERNAL
ALTER TABLE "IO_INTERNAL" MODIFY ("CORRESPONDENCEATTACHMENTS" VARCHAR2(200));
ALTER TABLE "IO_INTERNAL" MODIFY ("REMARKS" VARCHAR2(1000));

-- ⚠️  TABLE: IO_INCOMING
ALTER TABLE "IO_INCOMING" MODIFY CONSTRAINT "FK_IO_INCOMING_IO_RECEIVEMODES" DISABLE NOVALIDATE;
ALTER TABLE "IO_INCOMING" STORAGE ( NEXT 1048576)  ;

-- ⚠️  TABLE: IO_FORWARDINGSHISTORY
ALTER TABLE "IO_FORWARDINGSHISTORY" MODIFY ("INSTRUCTIONS" VARCHAR2(4000));
ALTER TABLE "IO_FORWARDINGSHISTORY" STORAGE ( NEXT 1048576)  ;

-- ⚠️  TABLE: IO_EMPLOYEESCONFIGS
ALTER TABLE "IO_EMPLOYEESCONFIGS" MODIFY ("SYSTEMTYPE" VARCHAR2(20) DEFAULT 0);
-- ⚠️  ALTER TABLE "IO_EMPLOYEESCONFIGS" DROP CONSTRAINT "IO_EMPLOYEESCONFIGS_NEW_PK";

-- ⚠️  TABLE: IO_EMPLOYEES
-- ⚠️  ALTER TABLE "IO_EMPLOYEES" DROP CONSTRAINT "IO_EMPLOYEES_NEW_PK";
-- ⚠️  ALTER TABLE "IO_EMPLOYEES" DROP CONSTRAINT "IO_EMPLOYEES_UK1";
-- ⚠️  ALTER TABLE "IO_EMPLOYEES" DROP CONSTRAINT "IO_EMPLOYEES_UK2";

-- ⚠️  TABLE: ARCHIVE_RULE
ALTER TABLE "ARCHIVE_RULE" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193744".nextval);
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "PK_ARCHIVE_RULE";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "FK_ARCHIVE_RULE_DEPT";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "FK_ARCHIVE_RULE_FIELD";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "FK_ARCHIVE_RULE_TARGET_FIELD";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "UK_ARCHIVE_RULE_DEPT_FIELD";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "CHK_ARCHIVE_RULE_NOT_SELF";
-- ⚠️  ALTER TABLE "ARCHIVE_RULE" DROP CONSTRAINT "CHK_ARCHIVE_RULE_OPERATOR";
ALTER TABLE "ARCHIVE_RULE" ADD  PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "ARCHIVE_RULE" ADD CONSTRAINT "FK5536X2WFP92LFPU6CFLDV2YTD" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "ARCHIVE_DEPARTMENT"("ID") ENABLE;
ALTER TABLE "ARCHIVE_RULE" ADD CONSTRAINT "FKFNQIH76KL2034B5MHS46OS1IC" FOREIGN KEY ("FIELD_ID") REFERENCES "ARCHIVE_FIELDS"("ID") ENABLE;
ALTER TABLE "ARCHIVE_RULE" ADD CONSTRAINT "FKMHAU5YIOS85WBJSWVGALI2G1P" FOREIGN KEY ("TARGET_FIELD_ID") REFERENCES "ARCHIVE_FIELDS"("ID") ENABLE;
ALTER TABLE "ARCHIVE_RULE" ADD  CHECK (operator in ('EQUALS','NOT_EQUALS','CONTAINS','STARTS_WITH')) ENABLE;

-- ⚠️  TABLE: ARCHIVE_FIELD_MAPPINGS
ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193634".nextval);
-- ⚠️  ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" DROP CONSTRAINT "PK_ARCHIVE_FIELD_MAPPINGS";
-- ⚠️  ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" DROP CONSTRAINT "FK_AFM_DEPT";
-- ⚠️  ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" DROP CONSTRAINT "UK_ARCHIVE_FIELD_MAPPINGS";
ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" ADD  PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" ADD CONSTRAINT "FK45YO76DVO9B7TILESTJ3N1FBS" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "ARCHIVE_DEPARTMENT"("ID") ENABLE;
ALTER TABLE "ARCHIVE_FIELD_MAPPINGS" ADD CONSTRAINT "UKMCDK0ETTSUT0JGS0PTQYYNBVC" UNIQUE ("DEPARTMENT_ID","FIELD_ID","FILENET_CLASS") ENABLE;

-- ⚠️  TABLE: ARCHIVE_DEPARTMENT
ALTER TABLE "ARCHIVE_DEPARTMENT" DROP ("ACTIVE");
ALTER TABLE "ARCHIVE_DEPARTMENT" MODIFY ("ID" NUMBER(19,0) DEFAULT "ISEQ$$_193830".nextval);
-- ⚠️  ALTER TABLE "ARCHIVE_DEPARTMENT" DROP CONSTRAINT "PK_ARCHIVE_DEPARTMENT";
-- ⚠️  ALTER TABLE "ARCHIVE_DEPARTMENT" DROP CONSTRAINT "UK_ARCHIVE_DEPARTMENT_CODE";
ALTER TABLE "ARCHIVE_DEPARTMENT" ADD  PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "ARCHIVE_DEPARTMENT" ADD CONSTRAINT "UKSPV2PJ23CP8GDBH0AEUXTTDYA" UNIQUE ("CODE") ENABLE;
