-- ==================================================================
--  [04] INDEXES  (New: 22  Changed: 4)
--  New = safe. Changed = DROP + CREATE (no data loss).
--  Target schema : MOAMALAT
--  Run as        : DBA or MOAMALAT user
-- ==================================================================


-- ──────────────────────────────────────────────────────────────────
-- NEW INDEXES  (22)
-- ──────────────────────────────────────────────────────────────────

-- NEW INDEX: UKFR0VW4UML3M68UI3ICAIEM7A5
CREATE UNIQUE INDEX "UKFR0VW4UML3M68UI3ICAIEM7A5" ON "ARCHIVE_FIELD_OPTIONS" ("FIELD_ID","VALUE_EN") ;

-- NEW INDEX: IX_MENTIONS_CORR
CREATE INDEX "IX_MENTIONS_CORR" ON "USER_MENTIONS" ("ISDELETED","CORRESPONDENCE_NUMBER","HIJRI_YEAR","CORRESPONDENCE_TYPE") ;

-- NEW INDEX: IDX_DELEGATION_ACTIVE_ENDDATE
CREATE INDEX "IDX_DELEGATION_ACTIVE_ENDDATE" ON "EMPLOYEE_DELEGATION" ("IS_ACTIVE","END_DATE") ;

-- NEW INDEX: UK61L8UYCX7YYKRS2GJUVBCMYUU
CREATE UNIQUE INDEX "UK61L8UYCX7YYKRS2GJUVBCMYUU" ON "WF_QUEUE_USERS" ("QUEUE_NAME","USERNAME") ;

-- NEW INDEX: IDX_TASK_CORRESP
CREATE INDEX "IDX_TASK_CORRESP" ON "TASKS" ("CORRESPONDENCE_TYPE","CORRESPONDENCE_SEQ","CORRESPONDENCE_YEAR") ;

-- NEW INDEX: PK_MOAMALAT_PERMISSIONS
CREATE UNIQUE INDEX "PK_MOAMALAT_PERMISSIONS" ON "MOAMALAT_PERMISSIONS" ("ID") ;

-- NEW INDEX: UKJHFR0HI8VAQ0J4HILXISD23S2
CREATE UNIQUE INDEX "UKJHFR0HI8VAQ0J4HILXISD23S2" ON "ARCHIVE_FIELDS" ("DEPARTMENT_ID","NAME") ;

-- NEW INDEX: UKIAD9GA0T7ABP829NS5B0VYO7Q
CREATE UNIQUE INDEX "UKIAD9GA0T7ABP829NS5B0VYO7Q" ON "ARCHIVE_MAPPINGS" ("DEPARTMENT_ID")
  PCTFREE 10 INITRANS 2 LOGGING ;

-- NEW INDEX: IO_EMPLOYEES_PROD_2024-11-11_IXR01
CREATE INDEX "IO_EMPLOYEES_PROD_2024-11-11_IXR01" ON "IO_EMPLOYEES_PROD_2024_11_11" (LOWER("USERID")) ;

-- NEW INDEX: UQ_MOAMALAT_PERMISSIONS_CODE
CREATE UNIQUE INDEX "UQ_MOAMALAT_PERMISSIONS_CODE" ON "MOAMALAT_PERMISSIONS" ("PERMISSION_CODE") ;

-- NEW INDEX: IO_EMPLOYEES_PROD_2024-11-11_UK1
CREATE UNIQUE INDEX "IO_EMPLOYEES_PROD_2024-11-11_UK1" ON "IO_EMPLOYEES_PROD_2024_11_11" ("USERID") ;

-- NEW INDEX: PK_MOAMALAT_PERMISSION_ASSIGN
CREATE UNIQUE INDEX "PK_MOAMALAT_PERMISSION_ASSIGN" ON "MOAMALAT_PERMISSION_ASSIGNMENTS" ("ID") ;

-- NEW INDEX: UKSPV2PJ23CP8GDBH0AEUXTTDYA
CREATE UNIQUE INDEX "UKSPV2PJ23CP8GDBH0AEUXTTDYA" ON "ARCHIVE_DEPARTMENT" ("CODE") ;

-- NEW INDEX: IX_MENTIONS_USER
CREATE INDEX "IX_MENTIONS_USER" ON "USER_MENTIONS" ("ISDELETED","MENTIONED_USER_ID") ;

-- NEW INDEX: UKMCDK0ETTSUT0JGS0PTQYYNBVC
CREATE UNIQUE INDEX "UKMCDK0ETTSUT0JGS0PTQYYNBVC" ON "ARCHIVE_FIELD_MAPPINGS" ("DEPARTMENT_ID","FIELD_ID","FILENET_CLASS") ;

-- NEW INDEX: UK_MOAMALAH_UNQ
CREATE UNIQUE INDEX "UK_MOAMALAH_UNQ" ON "MOAMALAH" ("CORRESPONDENCE_NUMBER","HIJRI_YEAR","TYPE_ID")
  PCTFREE 10 INITRANS 2 LOGGING ;

-- NEW INDEX: UK_IO_REM_SCHED
CREATE UNIQUE INDEX "UK_IO_REM_SCHED" ON "IO_REMINDERS" ("CORRESPONDENCENUMBER","HIJRICYEAR","TYPEID","USER_ID") ;

-- NEW INDEX: IDX_COMMENT_LOOKUP
CREATE INDEX "IDX_COMMENT_LOOKUP" ON "CONVERSATION_COMMENT" ("CONVERSATION_ID","DELETED") ;

-- NEW INDEX: IDX_CONV_LOOKUP
CREATE INDEX "IDX_CONV_LOOKUP" ON "CONVERSATION" ("CORRESPONDENCE_NUMBER","HIJRI_YEAR","CORRESPONDENCE_TYPE","DELETED") ;

-- NEW INDEX: IO_EMPLOYEES_PROD_2024-11-11_NEW_PK
CREATE UNIQUE INDEX "IO_EMPLOYEES_PROD_2024-11-11_NEW_PK" ON "IO_EMPLOYEES_PROD_2024_11_11" ("EMPLOYEEID") ;

-- NEW INDEX: PK_IO_REMINDERS
CREATE UNIQUE INDEX "PK_IO_REMINDERS" ON "IO_REMINDERS" ("ID") ;

-- NEW INDEX: UX_MENTIONS_UNIQUE_ACTIVE
CREATE UNIQUE INDEX "UX_MENTIONS_UNIQUE_ACTIVE" ON "USER_MENTIONS" (CASE "ISDELETED" WHEN 0 THEN "CORRESPONDENCE_NUMBER" END ,CASE "ISDELETED" WHEN 0 THEN "HIJRI_YEAR" END ,CASE "ISDELETED" WHEN 0 THEN "CORRESPONDENCE_TYPE" END ,CASE "ISDELETED" WHEN 0 THEN "MENTIONED_USER_ID" END ,CASE "ISDELETED" WHEN 0 THEN "PERMISSION_LEVEL" END ) ;


-- ──────────────────────────────────────────────────────────────────
-- CHANGED INDEXES  (4)  — DROP + CREATE
-- ──────────────────────────────────────────────────────────────────

-- CHANGED INDEX: IO_DELIVERYREPORTS_PK
DROP INDEX "IO_DELIVERYREPORTS_PK";
  CREATE UNIQUE INDEX "IO_DELIVERYREPORTS_PK" ON "IO_DELIVERYREPORTS" ("DELIVERYREPORTID","REPORTHIJRICYEAR") ;

-- CHANGED INDEX: IO_ACTIONS_PK
DROP INDEX "IO_ACTIONS_PK";
  CREATE UNIQUE INDEX "IO_ACTIONS_PK" ON "IO_ACTIONS" ("ACTIONID") ;

-- CHANGED INDEX: IO_REASONS_PK
DROP INDEX "IO_REASONS_PK";
  CREATE UNIQUE INDEX "IO_REASONS_PK" ON "IO_REJECTIONREASONS" ("REASONID") ;

-- CHANGED INDEX: IO_DELIVERYREPORTITEMS_PK
DROP INDEX "IO_DELIVERYREPORTITEMS_PK";
  CREATE UNIQUE INDEX "IO_DELIVERYREPORTITEMS_PK" ON "IO_DELIVERYREPORTITEMS" ("REPORTNUMBER","REPORTHIJRICYEAR","CORRESPONDENCENUMBER","HIJRICYEAR","DESTINATIONID") ;
