-- ==================================================================
--  [09] TRIGGERS  (2)
--  Safe — CREATE OR REPLACE TRIGGER
--  Target schema : MOAMALAT
--  Run as        : DBA or MOAMALAT user
-- ==================================================================

-- New TRIGGER: TRG_MOAMALAT_PERM_ASSIGN_UPD
CREATE OR REPLACE TRIGGER "TRG_MOAMALAT_PERM_ASSIGN_UPD"
  BEFORE UPDATE ON "MOAMALAT_PERMISSION_ASSIGNMENTS"
  REFERENCING FOR EACH ROW
  BEGIN
  :NEW.DATE_UPDATED := SYSTIMESTAMP;
END;
/
/

-- New TRIGGER: TRG_MOAMALAT_PERMISSIONS_UPD
CREATE OR REPLACE TRIGGER "TRG_MOAMALAT_PERMISSIONS_UPD"
  BEFORE UPDATE ON "MOAMALAT_PERMISSIONS"
  REFERENCING FOR EACH ROW
  BEGIN
  :NEW.DATE_UPDATED := SYSTIMESTAMP;
END;
/
/
